language: node_js

node_js:
  - "stable"

services:
  - postgresql

cache:
  directories:
  - node_modules

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  - TEST_DIR=client
  - TEST_DIR=server

script:
  - cd $TEST_DIR
  - npm install
  - npm test
  - npm run build
